import type { CatalogSortOption, ProductCategory } from "@/lib/contracts";

export const PRODUCT_CATEGORY_LABELS: Record<ProductCategory, string> = {
  ELECTRONICA: "Electronica",
  HOGAR: "Hogar",
  ACCESORIOS: "Accesorios",
};

export const CATALOG_SORT_LABELS: Record<CatalogSortOption, string> = {
  featured: "Destacados",
  "price-asc": "Precio: menor a mayor",
  "price-desc": "Precio: mayor a menor",
  newest: "Mas recientes",
};

export const appCopy = {
  metadata: {
    title: "Vendora",
    description: "Tienda y backoffice del MVP de Vendora.",
  },
  storefrontHeader: {
    brand: "Vendora tienda",
    tagline: "Catalogo real, carrito persistente y checkout con Mercado Pago.",
    browse: "Inicio",
    categories: "Categorias",
    explore: "Explorar",
    admin: "Admin",
    cart: "Carrito",
  },
  storefrontCatalog: {
    heroEyebrow: "Tienda MVP en marcha",
    heroTitle: "Explora productos reales con filtros claros y una navegacion simple.",
    heroDescription:
      "Vendora prioriza descubrir rapido por categoria, precio y busqueda sin perder el acceso al carrito ni al detalle de producto.",
    searchPlaceholder: "Buscar por producto o SKU",
    searchSubmit: "Buscar",
    searchPending: "Buscando...",
    filterToggle: "Filtros",
    filterClose: "Cerrar filtros",
    filtersTitle: "Filtrar catalogo",
    filtersDescription:
      "Ajusta categoria, precio y orden para encontrar mas rapido lo que buscas.",
    categoryLabel: "Categoria",
    minPriceLabel: "Precio minimo",
    maxPriceLabel: "Precio maximo",
    sortLabel: "Ordenar por",
    applyFilters: "Aplicar filtros",
    clearFilters: "Limpiar",
    quickCategoriesTitle: "Explorar por categoria",
    resultsEyebrow: "Catalogo activo",
    resultsTitle: "Descubre productos listos para comprar",
    allProducts: "Todos los productos activos",
    filteredProducts: "Resultados filtrados",
    resultCountSuffix: "productos",
    categoryCountSuffix: "items",
    emptyTitle: "No encontramos productos con esos filtros.",
    emptyDescription:
      "Prueba con otra categoria, un rango de precio mas amplio o una busqueda mas corta.",
    retryTitle: "El catalogo no esta disponible por el momento.",
    retryAction: "Reintentar catalogo",
    imagePending: "Imagen pendiente",
    variantsSuffix: "variantes",
    startingAt: "Desde",
    noPrice: "Consultar precio",
    viewProduct: "Ver producto",
    activeFiltersTitle: "Filtros activos",
    featuredHighlights: [
      "Busqueda por producto o SKU",
      "Categorias visibles desde la portada",
      "Orden y rango de precio para navegar mejor",
    ],
  },
  productDetail: {
    missingEyebrow: "Producto no disponible",
    missingTitle: "Este producto ya no aparece en el catalogo activo.",
    missingDescription: "Vuelve al catalogo para seguir explorando opciones disponibles.",
    backToCatalog: "Volver al catalogo",
    temporaryError: "No pudimos cargar el detalle del producto.",
    reviewCart: "Ver carrito",
    detailEyebrow: "Detalle del producto",
    chooseVariant: "Elige una variante",
    selectedPrice: "Precio seleccionado",
    addToCart: "Agregar variante al carrito",
    goToCart: "Ir al carrito",
    variantSku: "SKU",
    stockLabel: "Stock disponible",
    stockReady: "Listo para compra inmediata",
    stockLow: "Ultimas unidades disponibles",
    stockOut: "Sin stock por ahora",
    stockUnknown: "Stock a confirmar",
    addedToCart: "agregado al carrito",
    categoryLabel: "Categoria",
  },
  cart: {
    emptyEyebrow: "Carrito listo para empezar",
    emptyTitle: "Tu carrito esta vacio.",
    emptyDescription: "Explora el catalogo y agrega al menos una variante para preparar el checkout.",
    returnToCatalog: "Volver al catalogo",
    eyebrow: "Resumen de compra",
    title: "Revisa tus productos y confirma el envio antes de pagar.",
    continueBrowsing: "Seguir explorando",
    clearCart: "Vaciar carrito",
    remove: "Quitar",
    quantityLabel: "Cantidad",
    orderSummaryEyebrow: "Checkout guiado",
    orderSummaryTitle: "Completa tus datos y te llevamos a Mercado Pago.",
    orderSummaryDescription:
      "Primero guardamos el pedido en Vendora y despues generamos el link de pago. Asi mantienes una referencia clara aunque cierres la ventana.",
    subtotal: "Subtotal",
    deliveryScopeTitle: "Cobertura actual",
    deliveryScopeDescription:
      "En este MVP solo hacemos envios dentro de CABA y AMBA. Si completas una direccion fuera de esa zona, el checkout no avanza.",
    contactSection: "Contacto",
    shippingSection: "Entrega",
    fullName: "Nombre completo",
    email: "Email",
    phone: "Telefono",
    recipientName: "Quien recibe",
    shippingPhone: "Telefono para la entrega",
    postalCode: "Codigo postal",
    streetAddress: "Direccion",
    streetAddressHint: "Calle, altura, piso y departamento",
    addressLine2: "Referencia adicional (opcional)",
    locality: "Localidad",
    province: "Provincia",
    deliveryNotes: "Indicaciones de entrega (opcional)",
    ambaOnly: "Envios disponibles solo en CABA y AMBA.",
    preparing: "Preparando checkout...",
    continueToPayment: "Continuar a Mercado Pago",
  },
  checkoutStatus: {
    success: {
      eyebrow: "Pago enviado correctamente",
      title: "Tu pago fue enviado a validacion.",
      description: "La confirmacion final sigue llegando por webhook, pero el pedido ya quedo registrado y el flujo de pago se completo correctamente.",
      actionLabel: "Volver al catalogo",
      actionHref: "/",
    },
    pending: {
      eyebrow: "Pago en revision",
      title: "Mercado Pago todavia esta procesando la confirmacion.",
      description: "Guarda la referencia del pedido y espera la actualizacion final del pago.",
      actionLabel: "Revisar carrito",
      actionHref: "/cart",
    },
    failure: {
      eyebrow: "Pago no completado",
      title: "El pago no pudo completarse.",
      description: "Puedes volver al carrito, revisar tus datos y reintentar cuando quieras.",
      actionLabel: "Volver al carrito",
      actionHref: "/cart",
    },
    orderReference: "Referencia del pedido",
    paymentReference: "Referencia del pago",
    snapshotLabel: "Ultimo checkout guardado",
    fallbackOrder: "Disponible cuando llegue la redireccion",
    fallbackPayment: "Sin referencia informada en la redireccion",
    browseCatalog: "Explorar catalogo",
  },
  adminLogin: {
    eyebrow: "Acceso administrativo",
    title: "Ingresa para gestionar catalogo, stock y pedidos.",
    description:
      "Este espacio es solo para el equipo de Vendora. La tienda publica sigue separada para compradores.",
    credentialHint:
      "Usa las credenciales iniciales configuradas por entorno para el primer acceso.",
    sessionHint:
      "Las actualizaciones de productos, stock y pedidos requieren una sesion administrativa activa.",
    sectionEyebrow: "Inicio de sesion",
    sectionTitle: "Abre una sesion protegida.",
    backToStore: "Volver a la tienda",
    emailLabel: "Email admin",
    emailPlaceholder: "ops@vendora.local",
    passwordLabel: "Contrasena",
    passwordPlaceholder: "Minimo 8 caracteres",
    submit: "Ingresar al admin",
    submitting: "Ingresando...",
  },
  adminDashboard: {
    eyebrow: "Operacion administrativa",
    title:
      "Gestiona catalogo, inventario y pedidos AMBA desde un espacio protegido.",
    signedInPrefix: "Sesion iniciada como",
    backToStore: "Ir a la tienda",
    logout: "Cerrar sesion",
    summaryTitle: "Panel operativo",
    summaryDescription:
      "Prioriza catalogo y pedidos activos sin perder visibilidad del estado general.",
    productsCard: "Productos cargados",
    activeProductsCard: "Activos en tienda",
    ordersCard: "Pedidos visibles",
    sectionCatalog: "Catalogo",
    sectionOrders: "Pedidos",
  },
  adminProductEditor: {
    workspaceEyebrow: "Gestion de productos",
    workspaceTitle: "Catalogo listo para editar",
    workspaceDescription:
      "Selecciona un producto existente o crea uno nuevo con secciones guiadas para informacion, variantes e imagenes.",
    newProduct: "Nuevo producto",
    emptyProducts: "Todavia no hay productos cargados en el catalogo admin.",
    draftLabel: "Borrador nuevo",
    createTitle: "Crear producto",
    editTitle: "Editar producto",
    basics: "Informacion principal",
    merchandising: "Publicacion y categoria",
    variants: "Variantes e inventario",
    images: "Imagenes",
    name: "Nombre del producto",
    slug: "Slug",
    description: "Descripcion",
    status: "Estado",
    category: "Categoria",
    addVariant: "Agregar variante",
    removeVariant: "Quitar variante",
    variantName: "Nombre de variante",
    variantSku: "SKU",
    variantPrice: "Precio",
    variantCurrency: "Moneda",
    variantStock: "Stock disponible",
    addImage: "Agregar imagen",
    removeImage: "Quitar imagen",
    imageUrl: "URL de imagen",
    imageKey: "Cloudinary asset key",
    imageAlt: "Texto alternativo",
    imageSortOrder: "Orden",
    helper: "El estado `ARCHIVED` retira el producto de la tienda. Usa stock por variante para reflejar disponibilidad real.",
    saving: "Guardando producto...",
    saveChanges: "Guardar cambios",
    createProduct: "Crear producto",
  },
  adminOrders: {
    eyebrow: "Visibilidad de pedidos",
    title: "Cola operativa de pedidos y fulfillment",
    filterLabel: "Filtrar por fulfillment",
    allQueues: "Todas las colas",
    ordersCount: "pedidos",
    emptyAll: "Todavia no hay pedidos en la cola operativa.",
    emptyFilteredPrefix: "No hay pedidos en estado",
    commercial: "Comercial",
    fulfillment: "Fulfillment",
    payment: "Pago",
    notes: "Notas operativas",
    reference: "Referencia de entrega",
    addNote: "Agrega una nota breve para el equipo",
    addReference: "Ruta, chofer o referencia interna",
    awaitingPayment: "Esperando confirmacion de pago",
    currentReference: "Referencia actual",
    cancel: "Cancelar pedido",
    cancelling: "Cancelando...",
    locked: "Pedido bloqueado",
    advance: "Mover a",
    advancing: "Actualizando...",
    done: "Fulfillment completo",
    waitPayment: "Espera pago antes de avanzar",
    cannotCancelPaid: "Los pedidos pagos quedan bloqueados para mantener la integridad del flujo.",
    orderItems: "Contenido del pedido",
  },
};

export function getProductCategoryLabel(category: ProductCategory) {
  return PRODUCT_CATEGORY_LABELS[category];
}

export function getCatalogSortLabel(sort: CatalogSortOption) {
  return CATALOG_SORT_LABELS[sort];
}
